
# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

echo '==============================='
echo INFRA SHELL CONFIGURATION ZSHRC
echo '==============================='

# Path to your Oh My Zsh installation.
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# temp workaround
export DIR_DOTFILES=/tmp/.dotfiles

# === History Settings ===
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/${DIR_DOTFILES}/.zsh_history
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_FIND_NO_DUPS
setopt EXTENDED_HISTORY


# === Aliases ===
alias k_mt='export KUBECONFIG=~/.kube/configMT'
alias k_st='export KUBECONFIG=~/.kube/configST'
alias k_ctx='kubectx'
alias k_ns='kubens'
alias cls='clear'
alias lse='eza --long --header --icons --git'


# Set the path for oh-my-zsh
export ZSH="${DIR_DOTFILES}/.oh-my-zsh"

# Load oh-my-zsh if installed
if [ -d "$ZSH" ]; then
  source "$ZSH/oh-my-zsh.sh"
fi

# Load antigen if available
if [ -f "${DIR_DOTFILES}/antigen.zsh" ]; then
  # Load Antigen
  source ~/antigen.zsh
  # Load Antigen configurations
  antigen init ~/.antigenrc
fi

# Initialize Starship prompt
if command -v starship >/dev/null 2>&1; then
  eval "$(starship init zsh)"
fi

function sudo {
    ${HOME}/.local/bin/pam_tid.py --check || echo "Enabling Touch ID for sudo..."; /usr/bin/sudo ${HOME}/.local/bin/pam_tid.py
    /usr/bin/sudo "$@"
}

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
eval "$(/opt/homebrew/bin/brew shellenv)"

complete -C $(which aws_completer) aws
autoload bashcompinit && bashcompinit
autoload -Uz compinit && compinit

[ -f ~/.resh/shellrc ] && source ~/.resh/shellrc # this line was added by RESH
